# Generated by Django 2.2.2 on 2019-08-04 06:21

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppAuthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_kit_id', models.CharField(max_length=25, unique=True)),
                ('phone_number', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'app_auth_data',
            },
        ),
        migrations.CreateModel(
            name='catch_email_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'catch_email_temp',
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'notification_type',
            },
        ),
        migrations.CreateModel(
            name='organiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=16)),
                ('organiser_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'organiser',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'subscription_type',
            },
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('logo', models.ImageField(upload_to='team_logo')),
                ('owner', models.CharField(max_length=128)),
                ('manager', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('intro', models.TextField()),
                ('tournament_detail_image', models.ImageField(blank=True, upload_to='tournament_image')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.organiser')),
            ],
            options={
                'db_table': 'tournament',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=65, unique=True)),
                ('date_of_birth', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('app_auth_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.AppAuthData')),
                ('subscription_type_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.SubscriptionType')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.NotificationType')),
                ('user_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.UserInfo')),
            ],
            options={
                'db_table': 'user_notification_type',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('device_name', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.UserInfo')),
            ],
            options={
                'db_table': 'user_log',
            },
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('jersey_number', models.CharField(max_length=16)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.team')),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='match_images')),
                ('home_score', models.CharField(max_length=4)),
                ('away_score', models.CharField(max_length=4)),
                ('team_away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_away', to='models.team')),
                ('team_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_home', to='models.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='models.tournament')),
                ('winner', models.ForeignKey(default='Not Declared', on_delete=django.db.models.deletion.CASCADE, related_name='team_winner', to='models.team')),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='tournament_team_relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.tournament')),
            ],
            options={
                'db_table': 'tournament_team_relationship',
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
