# Generated by Django 2.2.1 on 2019-07-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_on', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'notification_type',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'subscription_type',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='catch_email_temp',
            table='catch_email_temp',
        ),
        migrations.CreateModel(
            name='UserNotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.NotificationType')),
                ('user_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.UserInfo')),
            ],
            options={
                'db_table': 'user_notification_type',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='subscription_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='models.SubscriptionType'),
        ),
    ]
