# Generated by Django 2.2.2 on 2019-08-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
