# Generated by Django 2.2.2 on 2019-08-04 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20190804_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationtype',
            name='user_info_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.AppAuthData'),
        ),
    ]
