# Generated by Django 2.2.2 on 2019-09-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20190915_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='H1K1ZfYupkXxsMcv0Y0QHJ1cjGQe6iPf', max_length=32),
        ),
    ]
