# Generated by Django 2.2.2 on 2019-09-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20190915_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(default=None, upload_to='carousel_images')),
                ('video_link', models.CharField(max_length=255)),
                ('match_opponent1', models.CharField(max_length=20)),
                ('match_opponent2', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'carousel_details',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='dUjS1npcChijE0V3scQG4woKPQJ8jL29', max_length=32),
        ),
    ]
