# Generated by Django 2.2.2 on 2019-08-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20190805_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotificationtype',
            old_name='user_info_id',
            new_name='app_auth_data',
        ),
    ]
