# Generated by Django 2.2.2 on 2019-08-07 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20190805_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
