# Generated by Django 2.2.2 on 2019-09-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20190915_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='video_link',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='bh4RuuTXn5hswwGmPDaBSW35tpJztANU', max_length=32),
        ),
    ]
