# Generated by Django 2.2.2 on 2019-08-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_userlog_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
