# Generated by Django 2.2.2 on 2019-09-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20190915_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='active_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='EfOjmnUAUAGWfBRbFT9VCERX1yQwWMo2', max_length=32),
        ),
    ]
