# Generated by Django 2.2.2 on 2019-08-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_userinfo_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
