# Generated by Django 2.2.2 on 2019-09-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20190915_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image',
            field=models.ImageField(blank=True, upload_to='carousel_images_mobile'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='xJWkPaDp3MuXp5l0p1hpOA2GtM1jLnCK', max_length=32),
        ),
    ]
