# Generated by Django 2.2.2 on 2019-08-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_userinfo_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='bbMo8NBtNStYa07KXg5zRanrhI62zatn', max_length=32),
        ),
    ]
