# Generated by Django 2.2.2 on 2019-09-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20190916_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='carousel_image_mobile',
            field=models.ImageField(blank=True, upload_to='carousel_images_mobile'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image',
            field=models.ImageField(blank=True, upload_to='carousel_images'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='zwjpJrmZMB3euJOBJA172uXoSmFLTvL2', max_length=32),
        ),
    ]
