# Generated by Django 2.2.2 on 2019-08-20 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20190818_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='hb8swRVqVWGDlRQz6jy6FWZqpbFzqaZq', max_length=32),
        ),
    ]
