# Generated by Django 2.2.2 on 2019-08-20 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20190820_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='xGPiT04oSQzv1diTS5Lxwg3yu0RT2otq', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 15, 35, 17, 474672)),
        ),
    ]
