# Generated by Django 2.2.2 on 2019-08-20 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20190820_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='NnUXC3a8wycsra07rhbwmv94VFjabJGY', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 10, 21, 43, 368582, tzinfo=utc)),
        ),
    ]
