# Generated by Django 2.2.2 on 2019-08-31 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20190820_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='eeCv0V8WPwIZhACEyNA0gpIAqCRQHUkB', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 8, 58, 47, 905282, tzinfo=utc)),
        ),
    ]
