# Generated by Django 2.2.2 on 2019-09-03 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20190903_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='venue',
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='uzplTkzijlTUAI9qEoEJRnsQxdS0OFzD', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 3, 6, 25, 38, 747865, tzinfo=utc)),
        ),
    ]
