# Generated by Django 2.2.2 on 2019-09-08 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20190903_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email_token',
            field=models.CharField(default='S6BAT1CzPbPzTBcf7OI2OXwefocl7mKw', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 8, 9, 53, 45, 957208, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_status', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.UserInfo')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
